FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/environmental-monitoring /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
